[project]
name = "nog"
version = "0.2"
description = "Nixos Generations Management"
readme = "README.md"
authors = [{ name = "Simon Kennedy", email = "sffjunkie+code@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["rich>=14.0.0", "typer>=0.15.2"]

[project.scripts]
nog = "nog.cli.main:app"

[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"
